# Generated by Django 2.2.6 on 2020-08-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='column',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='row',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
