# Generated by Django 2.2.6 on 2020-08-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20200807_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
